### ISSUE TITLE
React-Router example

### ISSUE THREAD

**Issue by nkbt** [in-flux/component-router#40]
Show how Component Router can work together with react-router.

**Comment by nkbt** [comment]
@halhenke how do you feel about this one? Sounds interesting to do?

**Comment by halhenke** [comment]
Yeah I could have a go - is this just documentation or do we want to make an example app that combines them?

**Comment by nkbt** [comment]
Example app would be ideal. You can take for example FooBar example and extract it into a separate repo. But you can try to make one inside `Examples`folder as well.

**Comment by nkbt** [comment]
https://github.com/in-flux/example-with-react-router just created an empty repo for this. Add `react-component-template` to it as a remote, so you will have all the basics there

**Comment by nkbt** [comment]
```sh
git remote add template git@github.com:nkbt/react-component-template.git
merge --no-ff --no-edit template/master
```

**Comment by halhenke** [comment]
OK sounds good. Will try and get started tonight probably (Have to look into `react-router` a bit also - never used it).

Speaking of examples - was just wondering about the `x` & `y` query parameters from the "Random Links" current example app that are never removed from the URL because there isnt a corresponding ComponentRouter/namespace. Is that something that we might want to fix or is that an intentional thing to show the persistence of state across page changes?

**Comment by nkbt** [comment]
Ha! Everyone asks about it. It is sort of intentional, shows that we do not remove existing query params unless they were added by ComponentRouter component itself.

RR is fairly easy to deal with. Actually if you make an example and find it is not working right away - still submit it and make a separate issue to fix it. I suppose something should be broken with HTML4 navigation mode. Though HTML5 should Just Work (tm)

**Comment by halhenke** [comment]
Ah makes sense :-)

Would be a pretty impressive demo to see them working together. Will get on it.

**Comment by nkbt** [comment]
:+1:

**Comment by halhenke** [comment]
Just to keep you up to date - have been playing with this and am having (different) issues with both HTML4 and HTML5 mode. Might just be the particular way I ended up putting it together - at any rate will push the example later tonight so you can have a look.

**Comment by nkbt** [comment]
Would be awesome, thanks! I'd really like to see what issues are, so probably would be able to either fix them or use RR+CR in a certain non-breaking way

**Comment by halhenke** [comment]
Yeah it might just be a configuration thing. The HTML4 stuff seems to basically be about both trying to manage/react to the path portion of the URL (which i see is something you are working on removing #64 ). I very quickly ended up with paths like this:
http://localhost:8080/?baz=bar&page=foobar#/?baz=foo&page=foobar

With HTML5 I am getting full page unload/reloads after travelling through the app in some orders but not others. Really not sure where its coming from at this stage. Anyway will put code up later.
