### ISSUE TITLE
Usage as Flux-only solution

### ISSUE THREAD

**Issue by nkbt** [in-flux/component-router#54]
Example without React components and only using Flux, as raised in https://github.com/edge/cronux/issues/1

**Comment by halhenke** [comment]
So this would be an example where components are hooking directly into the Store without a ComponentRouter? Sounds good.

Have been thinking maybe we could build another couple of Top Level/Wrapper Components that are maybe a little more straightforward for people to understand (maybe break them out into another package like [react-redux]?). ComponentRouter is super general but maybe not very intuitive for most people. Was thinking of something like a dedicated "ComponentSwitcher" to render different Components based on state and a dedicated "ComponentWrapper" to map query state to props of its Children. All stuff we can do already, but might be easier to visualize. Just a thought anyway.

**Comment by nkbt** [comment]
Great idea, you can mix it with react-swap!

And yes, just working directly with store, without url and componentRouter.

**Comment by halhenke** [comment]
Ah - hadn't seen that yet! Cool.

So not using Url or Location either? Maybe could do a couple of examples here also...

**Comment by nkbt** [comment]
Yeah, you can do it right in this repo
