### ISSUE TITLE
API 3.0

### ISSUE THREAD

**Issue by nkbt** [in-flux/component-router#79]
I want to heavily simplify the API of the core to the bare minimum. And move other parts into separate components. Different modules may live in the same package, not necessarily split into multiple repos, thought it looks as a good idea to me to keep them all separately.

So at the moment I see it as:

## `component-router` core - package
  - [keep] Store
  - [keep] Actions
  - [keep] Reducers
  - [new] Container, new container component, that expects function as children and will call it passing `query`. Sort of:

    ```js
    <RouterContainer>
      {query => <MyComponent value={query.myComponent} />}
    </RouterContainer>
    ```

## `component-router-browser-history`
  - [keep] Location/Html5

## `component-router-hash-history`
  - [keep] Location/Html4

## `component-router-switch`
  - [keep] ComponentRouter, basic switch-component, based on value of namespace renders different components

## `component-router-url`
  - [keep] Url

**Comment by nkbt** [comment]
@halhenke what do you think about this? Also makes sense to do #49 as part of this update, since every single package except core won't have any examples (or maybe will?)

**Comment by halhenke** [comment]
:+1: 

I like it a lot. Would have to see more examples with the usage of `RouterContainer`/think about it more but I suspect it will be easier for people to grasp then `ComponentRouter` and have a simpler implementation. And i think the whole thing kind of makes it feel more open for people to build their own components off the core API.

**Comment by nkbt** [comment]
I've got some examples with RouterContainer-ish sort of container in my current production app. I found it to be much easier to work with so this whole issue appeared =)

**Comment by halhenke** [comment]
Awesome. Yeah I guess you gotta get things out there and then you find out the best way they work.

Speaking of which - still hacking at that React-Templating thing. Think it could have potential but getting bogged down in decision paralysis, choice of third party tools, general misunderstandings and a tendency to obsess over details at the expense of a working product. Will try to clean it up and show you (along with an explanation of how i think it could/should work) then would very much appreciate your input/help if you get the chance. Could do with some realism.

**Comment by nkbt** [comment]
@halhenke sounds good!

**Comment by nkbt** [comment]
# Update 1

## component-router core - package

- Should not have React dependency. I want to use it within Angular app.

## ng-component-router-url

- Angular directive for Url

**Comment by halhenke** [comment]
Interesting. Redux is now Angular compatible isn't it?

**Comment by nkbt** [comment]
It always was. There is nothing React-specific.

**Comment by nkbt** [comment]
#81

**Comment by nkbt** [comment]
# Update 2
There is no need for separate `component-router-browser-history` and `component-router-hash-history`, they are included into  the core.

**Comment by nkbt** [comment]
# Update 3

## `react-component-router` - https://github.com/in-flux/react-component-router

Will have:

 - ComponentRouteContainer 

  ```js
        <ComponentRouteContainer>
          {({query: {page}}) => (
            <div>
              {page}
            </div>
          )}
        </ComponentRouteContainer>
  ```

- UrlContainer

  ```js
      <UrlContainer {...query}>
        {urlProps => <a {...urlProps} {...props}>{children}</a>}
      </UrlContainer>
  ```

- Url

  ```js
    <Url query={{page: 'quickstart'}} className={styles.tab}>Quickstart</Url>
  ```

- createComponentRouteHandler

  ```js
  const ComponenentRouteHandler = createComponentRouteHandler('page')({
    [NOT_FOUND]: () => <h1>Not Found.</h1>,
    quickstart: () => <h1>Quickstart</h1>,
    foobar: () => <h1>FooBar</h1>
  });

  <ComponenentRouteHandler defaultValue="quickstart" page={page} />
  ```

At the moment they are implemented in https://github.com/in-flux/component-router/blob/master/src/example/App.js

**Comment by nkbt** [comment]
# Update 4
- Instance of Redux store should be now passed to component-router. No more singleton shared store
- That enables to use component-router on the server (TODO adapter)
- Pathname routing is now fully supported
- `react-component-router` now has bunch of usable React components, all bindings are transferred from examples

**Comment by nkbt** [comment]
API is fairly stable for the moment, I'm quite happy using it daily, so will release v3 soon.

**Comment by halhenke** [comment]
:+1: 

![](http://i.giphy.com/qUUyTJkYe0I1O.gif)
